-- # TASK 3 # --

USE INVENTORY 

-- CREATING PROCEDURES

-- ADDSUPPLIER 

CREATE PROCEDURE ADDSUPPLIER @ID AS CHAR(5), @NAME AS VARCHAR(50),
                 @ADDR AS VARCHAR(60), @CITY AS VARCHAR(30),
                 @PHONE AS CHAR(14), @MAIL AS VARCHAR(60)
AS
BEGIN
    INSERT INTO SUPPLIER
    VALUES (@ID, @NAME, @ADDR, @CITY, @PHONE, @MAIL);

    SELECT * FROM SUPPLIER
    WHERE SID = @ID ;
END

-- CHECKING THE CREATED PROCEDURE

ADDSUPPLIER 'S0001', 'DOT AND DASH ENGINEERING', 'No.11, Awho, Dinesh Vihar',
            'CHENNAI', '8939893900', 'support@dnd.com';

--------------------------------------

-- ADDPRO

GO
CREATE PROCEDURE ADDPRO @ID CHAR(5), @DESC VARCHAR(60), 
                 @PRICE INT, @CAT VARCHAR(30), @SID CHAR(5)
AS
BEGIN 
    INSERT INTO PRODUCT
    VALUES (@ID, @DESC, @PRICE, @CAT, @SID);

    SELECT * FROM PRODUCT
    WHERE PID = @ID;
END 

-- CHECKING THE CREATED PROCEDURE

ADDPRO 'P0001', 'iPhone 16 Pro max', 140000, 'Electronics', 'S0001';

-- ADDCUST
GO
CREATE PROCEDURE ADDCUST @ID CHAR(5), @NAME VARCHAR(50), 
                 @ADDR VARCHAR(60), @CITY VARCHAR(40), 
                 @PHNO CHAR(14), @MAIL VARCHAR(40), @DOB DATE
AS
BEGIN
    INSERT INTO CUSTOMER 
    VALUES (@ID, @NAME, @ADDR, @CITY, @PHNO, @MAIL, @DOB);

    SELECT * FROM CUSTOMER
    WHERE CID = @ID;
END


-- CHECKING THE CREATED PROCEDURE

ADDCUST 'C0001', 'Krishna', 'No.44, xyz Street', 'Chennai', 
        '8900000001', 'ksureshkrishna@gmail.com', '09-11-1997'

-- ADDORDER
GO
CREATE PROCEDURE ADDORDER @ID CHAR(5), @CID CHAR(5), 
                          @PID CHAR(5), @QTY INT
AS 
BEGIN 
    DECLARE @ODATE DATE;
    SET @ODATE = CONVERT(DATE, GETDATE());

    INSERT INTO ORDERS
    VALUES (@ID, @ODATE, @CID, @PID, @QTY);

    SELECT * FROM ORDERS
    WHERE OID = @ID 
END

-- CHECKING THE PROCEDURE

ADDORDER 'O0001', 'C0001', 'P0001', 1

