-- # TASK - 2 # --

USE INVENTORY 


-- DISPLAY PID, PDESC, CATEGORY, SNAME, SCITY

SELECT PID, PDESC, CATEGORY, SNAME, SCITY
FROM PRODUCT P 
INNER JOIN SUPPLIER S
ON P.SID = S.SID


-- DISPLAY OID, ODATE, CNAME, CADDR, CPHONE, PDESC, PRICE, OQTY, AMOUNT

SELECT OID, ODATE, CNAME, CADDR, CPHONE, 
       PDESC, PRICE, OQTY, (PRICE*OQTY) AS 'AMOUNT'
FROM CUSTOMER C
INNER JOIN ORDERS O 
ON C.CID = O.CID 
INNER JOIN PRODUCT P 
ON P.PID = O.PID 


-- CREATE A VIEW WITH NAME "BILL" FOR THE ABOVE

GO
CREATE VIEW BILL
AS 
    SELECT OID, ODATE, CNAME, CADDR, CPHONE, 
        PDESC, PRICE, OQTY, (PRICE*OQTY) AS 'AMOUNT'
    FROM CUSTOMER C
    INNER JOIN ORDERS O 
    ON C.CID = O.CID 
    INNER JOIN PRODUCT P 
    ON P.PID = O.PID 
GO


-- CHECKING THE CREATED VIEW

SELECT * FROM BILL 


