-- # TASK 1 # --

-- CREATE INVENTORY DATABASE
CREATE DATABASE INVENTORY ;

-- SELECT THE DESIRED DATABASE
USE INVENTORY ;


-- CREATING SUPPLIER TABLE
CREATE TABLE SUPPLIER
(SID CHAR(5) PRIMARY KEY CHECK (SID LIKE 'S____'),
SNAME VARCHAR(50) NOT NULL,
SADDR VARCHAR(60) NOT NULL,
SCITY VARCHAR(30) DEFAULT('DELHI'),
SPHONE CHAR(14) UNIQUE,
SEMAIL VARCHAR(60) UNIQUE);


-- CRAETING PRODUCT TABLE
CREATE TABLE PRODUCT
(PID CHAR(5) PRIMARY KEY CHECK (PID LIKE 'P____'), 
PDESC VARCHAR(60) NOT NULL,
PRICE INT,
CATEGORY VARCHAR(60),
SID CHAR(5) FOREIGN KEY REFERENCES SUPPLIER(SID));


-- CREATING CUSTOMER TABLE
CREATE TABLE CUSTOMER
(CID CHAR(5) PRIMARY KEY CHECK (CID LIKE 'C____'),
CNAME VARCHAR(30) NOT NULL,
CADDR VARCHAR(60) NOT NULL,
CCITY VARCHAR(50) NOT NULL,
CPHONE CHAR(14) NOT NULL UNIQUE,
CMAIL CHAR(50) NOT NULL UNIQUE,
DOB DATE CHECK (DOB < '01-01-2020'));


-- CREATING ORDERS TABLE
CREATE TABLE ORDERS
(OID CHAR(5) PRIMARY KEY CHECK (OID LIKE 'O____'),
ODATE DATE,
CID CHAR(5) FOREIGN KEY REFERENCES CUSTOMER(CID),
PID CHAR(5) FOREIGN KEY REFERENCES PRODUCT(PID),
OQTY INT CHECK (OQTY >= 1));



-- CREATING STOCK TABLE
CREATE TABLE STOCK
(PID CHAR(5) FOREIGN KEY REFERENCES PRODUCT(PID),
SQTY INT CHECK(SQTY >= 0),
ROL INT CHECK(ROL>0),      -- REORDER LEVEL
MOQ INT CHECK(MOQ >= 5));  -- MINIMUM ORDER QUANTITY


-- VIEW ALL THE TABLE
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCT;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;
SELECT * FROM STOCK ;